#!/bin/bash
#
ll="/usr/local/include/snaps" && [[ ! -d ${ll} ]] && exit
clear
[[ "$(whoami)" != "root" ]] && {
echo -e "\033[1;33m[\033[1;31m| YOU HAVE NOT STARTED THE SCRIPT CORRECTLY, YOU MUST START AS ROOT USER |\033[1;33m] \033[1;37mYOU MUST RUN THE FOLLOWING COMMAND \033[1;33msudo -i\033[0m"
exit 0
}

declare -A cor=( [0]="\033[1;37m" [1]="\033[1;34m" [2]="\033[1;31m" [3]="\033[1;33m" [4]="\033[1;32m" )
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1 > /dev/null 2>&1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1 > /dev/null 2>&1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1 > /dev/null 2>&1
# [[ ! -d /usr/local/lib/rm ]] && exit
_hora=$(printf '%(%D-%H:%M:%S)T') 
#COLORES 
red=$(tput setaf 1)
gren=$(tput setaf 2)
yellow=$(tput setaf 3)
SCPdir="/etc/VPS-MX" && [[ ! -d ${SCPdir} ]] && exit 1
DIR="/etc/VPS-MX"
SCPusr="${SCPdir}/controlador" 
SCPfrm="${SCPdir}/herramientas" 
SCPinst="${SCPdir}/protocolos" 
SCPidioma="${SCPdir}/idioma"
#PROCESSADOR
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_usop=$(top -bn1 | sed -rn '3s/[^0-9]* ([0-9\.]+) .*/\1/p;4s/.*, ([0-9]+) .*/\1/p' | tr '\n' ' ')

#SISTEMA-USO DA CPU-MEMORIA RAM
ram1=$(free -h | grep -i mem | awk {'print $2'})
ram2=$(free -h | grep -i mem | awk {'print $4'})
ram3=$(free -h | grep -i mem | awk {'print $3'})

_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")

if [[ -e /etc/bash.bashrc-bakup ]]; then AutoRun="\033[1;32m[ON]"
elif [[ -e /etc/bash.bashrc ]]; then AutoRun="\033[1;31m[OFF]"
fi
# Funcoes Globais
msg () {
#ACTULIZADOR
                                                                                        																																																																																																																											[[ ! -d /usr/local/lib/rm ]] && exit														
[[ ! -e /etc/versin_script ]] && echo 1 > /etc/versin_script
v11=$(cat /etc/versin_script_new) 
v22=$(cat /etc/versin_script)
#[[ $v11 = $22 ]] && 
vesaoSCT="\033[1;37mVersion \033[1;32m$v22\033[1;31m]" #|| vesaoSCT="\033[1;32mUPDATE\033[1;91m[\033[1;32m$v11\033[1;31m]" 
aviso_bock () {
echo 'echo -e "\033[1;91m————————————————————————————————————————————————————\n       ¡SCRIPT BLOCKED BY CLONING|| CONTACT YOUR SUPPLIER ! \n————————————————————————————————————————————————————"' > /usr/bin/menu
echo 'echo -e "\033[1;91m————————————————————————————————————————————————————\n       ¡SCRIPT BLOCKED BY CLONING|| CONTACT YOUR SUPPLIER ! \n————————————————————————————————————————————————————"' > /usr/bin/VPS-MX
 rm -rf /etc/VPS-MX 
}
local colors="/etc/VPS-MX/colors"
if [[ ! -e $colors ]]; then
COLOR[0]='\033[1;37m' #BRAN='\033[1;37m'
COLOR[1]='\e[93m' #VERMELHO='\e[31m'
COLOR[2]='\e[32m' #VERDE='\e[32m'
COLOR[3]='\e[31m' #AMARELO='\e[33m'
COLOR[4]='\e[34m' #AZUL='\e[34m'
COLOR[5]='\e[95m' #MAGENTA='\e[35m'
COLOR[6]='\033[1;97m' #MAG='\033[1;36m'
COLOR[7]='\033[36m' #MAG='\033[36m'
else
local COL=0
for number in $(cat $colors); do
case $number in
1)COLOR[$COL]='\033[1;37m';;
2)COLOR[$COL]='\e[31m';;
3)COLOR[$COL]='\e[32m';;
4)COLOR[$COL]='\e[33m';;
5)COLOR[$COL]='\e[34m';;
6)COLOR[$COL]='\e[35m';;
7)COLOR[$COL]='\033[1;36m';;
8)COLOR[$COL]='\e[36m';;
esac
let COL++
done
fi
NEGRITO='\e[1m'
SEMCOR='\e[0m'
 case $1 in
  -ne)cor="${COLOR[1]}${NEGRITO}" && echo -ne "${cor}${2}${SEMCOR}";;
  -ama)cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verm)cor="${COLOR[3]}${NEGRITO}[!] ${COLOR[1]}" && echo -e "${cor}${2}${SEMCOR}";;
  -verm2)cor="${COLOR[3]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -azu)cor="${COLOR[6]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -azuc)cor="${COLOR[7]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -verd)cor="${COLOR[2]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -az)cor="${COLOR[4]}${NEGRITO}" && echo -e "${cor}${2}${SEMCOR}";;
  -bra)cor="${COLOR[0]}${SEMCOR}" && echo -e "${cor}${2}${SEMCOR}";;
  "-bar2"|"-bar")cor="\e[1;30m————————————————————————————————————————————————————" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
  -tit)echo -e "\e[91m≪━━─━━─━─━─━─━─━━─━━─━─━─◈─━━─━─━─━─━━─━─━━─━─━━─━≫   \e[0m\n \e[2;97m\e[3;93m ❯❯❯❯ 𝙎𝘾𝙍𝙄𝙋𝙏 𝙈𝙊𝘿 𝙇𝘼𝘾𝘼𝙎𝙄𝙏𝘼𝙈𝙓 Translate by malinda❮❮❮❮  \033[0m \033[1;31m[\033[1;32m$vesaoSCT\n\e[91m≪━━─━─━━━─━─━─━─━─━━─━─━─◈─━─━─━─━─━━━─━─━─━━━─━─━≫   \e[0m" && echo -e "${SEMCOR}${cor}${SEMCOR}";;
  -bar3) $([[ ! -e $(echo -e $(echo "2F7573722F6C6F63616C2F6C69622F726D"| sed 's/../\\x&/g;s/$/ /')) ]] && $( aviso_bock > /dev/null 2>&1)) && echo -e "${SEMCOR}${cor}${SEMCOR}";;
 esac
}
  	[[ ! -d /usr/local/lib/sped ]] && exit
  
  
  check_IP () {
Key="$(cat /etc/VPS-MX/key.txt)"
ADM=$(sed -n '1 p' /usr/bin/venip |cut -d' ' -f1)
#ADM=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}') && echo "$ADM" > /usr/bin/venip
  IP2="$(wget -qO- ifconfig.me)"
  permited=$(curl -sSL "http://$ADM:81/checkip")
  [[ $(echo $permited|grep "$IP2") = "" ]] && {
  clear && clear
  #echo -e "	\e[1;100mNOTIFICACION ENVIADO\e[0m "
 echo 'clear && echo -e "\e[1;91m==============================================================\n ¡📵KEY BANNED📵!  CONTACT YOUR SUPPLIER   \n==============================================================\n\n"' > /usr/bin/vps-mx && chmod +x /usr/bin/vps-mx  && clear
  echo 'clear && echo -e "\e[1;91m==============================================================\n ¡📵KEY BANNED📵!  CONTACT YOUR SUPPLIER    \n==============================================================\n\n"' > /usr/bin/VPS-MX && chmod +x /usr/bin/VPS-MX && clear 
  echo 'clear && echo -e "\e[1;91m==============================================================\n ¡📵KEY BANNED📵!  CONTACT YOUR SUPPLIER    \n==============================================================\n\n"' > /usr/bin/menu && chmod +x /usr/bin/menu && clear
 
rm -rf /etc/VPS-MX/menu
 rm -rf /etc/VPS-MX/controlador
 rm -rf /etc/VPS-MX/protocolos
 rm -rf /etc/VPS-MX/herramientas/ADMbot.sh
 
 clear; clear
 userid="${SCPdir}/ID"
 		 TOKEN="2012880601:AAEJ3Kk18PGDzW57LpTMnVMn_pQYQKW3V9w"
			URL="https://api.telegram.org/bot$TOKEN/sendMessage"
			MSG="👇= 📵IP BANDED📵 =👇    
 ══════◄••••►══════
 Version: $(cat /etc/versin_script_new)
 ══════◄••••►══════
 🆔: $(cat ${userid})
 ══════◄••••►══════
 Usuario: $(cat ${SCPdir}/message.txt)
 ══════◄••••►══════
 IP: $(cat ${SCPdir}/MEUIPvps)
 ══════◄••••►══════
"
curl -s --max-time 10 -d "chat_id=605531451&disable_web_page_preview=1&text=$MSG" $URL &>/dev/null

 sleep 2s
  exit && exit 
  } || {
  echo "acceso activado" >/bin/lacasita
  }
  exit && exit && exit
}

canbio_color () {
clear
msg -bar2
msg -tit
msg -ama "     SCRIP VPS-MX COLOR CONTROLLER"
msg -bar2
msg -ama "$(fun_trans "Selecione 7 cores"): "
echo -e '\033[1;37m [1] ###\033[0m'
echo -e '\e[31m [2] ###\033[0m'
echo -e '\e[32m [3] ###\033[0m'
echo -e '\e[33m [4] ###\033[0m'
echo -e '\e[34m [5] ###\033[0m'
echo -e '\e[35m [6] ###\033[0m'
echo -e '\033[1;36m [7] ###\033[0m'
msg -bar2
for number in $(echo {1..7}); do
msg -ne "$(fun_trans "Digite un Color") [$number]: " && read corselect
[[ $corselect != @([1-7]) ]] && corselect=1
cores+="$corselect "
corselect=0
done
echo "$cores" > /etc/VPS-MX/colors
msg -bar2
}
fun_trans () { 
local texto
local retorno
declare -A texto
SCPidioma="${SCPdir}/idioma"
[[ ! -e ${SCPidioma} ]] && touch ${SCPidioma}
local LINGUAGE=$(cat ${SCPidioma})
[[ -z $LINGUAGE ]] && LINGUAGE=es
[[ $LINGUAGE = "es" ]] && echo "$@" && return
[[ ! -e /usr/bin/trans ]] && wget -O /usr/bin/trans https://raw.githubusercontent.com/scriptsmx/script/master/Install/trans &> /dev/null
[[ ! -e /etc/VPS-MX/texto-mx ]] && touch /etc/VPS-MX/texto-mx
source /etc/VPS-MX/texto-mx
if [[ -z "$(echo ${texto[$@]})" ]]; then
#ENGINES=(aspell google deepl bing spell hunspell apertium yandex)
#NUM="$(($RANDOM%${#ENGINES[@]}))"
retorno="$(source trans -e bing -b es:${LINGUAGE} "$@"|sed -e 's/[^a-z0-9 -]//ig' 2>/dev/null)"
echo "texto[$@]='$retorno'"  >> /etc/VPS-MX/texto-mx
echo "$retorno"
else
echo "${texto[$@]}"
fi
}
function_verify () {
  permited=$(curl -sSL "https://www.dropbox.com/s/nmau2w8vebewpq3/control")
  [[ $(echo $permited|grep "${IP}") = "" ]] && {
  clear
  echo -e "\n\n\n\033[1;91m————————————————————————————————————————————————————\n      ¡THIS KEY DOES NOT MATCH THE INSTALLER! \n————————————————————————————————————————————————————\n\n\n"
  [[ -d /etc/VPS-MX ]] && rm -rf /etc/VPS-MX
  exit 1
  } || {
  ### INTALAR VERSION DE SCRIPT
  v1=$(curl -sSL "https://raw.githubusercontent.com/lacasitamx/version/master/vercion")
  echo "$v1" > /etc/versin_script
  echo "$v1" > /etc/versin_script_new
  }
}
atualiza_fun () {
fun_ip 
SCPinstal="$HOME/install"
verificar_arq () {
case $1 in
"menu"|"message.txt"|"ID")ARQ="${SCPdir}/";; #Menu
"usercodes")ARQ="${SCPusr}/";; #Panel SSRR
"C-SSR.sh"|"proxy.sh"|"wireguard.sh")ARQ="${SCPinst}/";; #Panel SSR
"openssh.sh")ARQ="${SCPinst}/";; #OpenVPN
"squid.sh")ARQ="${SCPinst}/";; #Squid
"dropbear.sh")ARQ="${SCPinst}/";; #Instalacao
"openvpn.sh")ARQ="${SCPinst}/";; #Instalacao
"ssl.sh")ARQ="${SCPinst}/";; #Instalacao
"shadowsocks.sh"|"proxy.sh"|"python.py")ARQ="${SCPinst}/";; #Instalacao
"Shadowsocks-libev.sh"|"slowdns.sh")ARQ="${SCPinst}/";; #Instalacao
"Shadowsocks-R.sh")ARQ="${SCPinst}/";; #Instalacao 
"v2ray.sh")ARQ="${SCPinst}/";; #Instalacao
"budp.sh")ARQ="${SCPinst}/";; #Instalacao
"name")ARQ="${SCPdir}/tmp/";; #Instalacao
"sockspy.sh"|"PDirect.py"|"PPub.py"|"PPriv.py"|"POpen.py"|"PGet.py"|"python.py")ARQ="${SCPinst}/";; #Instalacao
*)ARQ="${SCPfrm}/";; #Herramientas
esac
mv -f ${SCPinstal}/$1 ${ARQ}/$1
chmod +x ${ARQ}/$1
}
error_fun () {
msg -bar2 && msg -verm "ERROR between VPS<-->GENERATOR (Port 81 TCP)" && msg -bar2
[[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
exit 1
}
invalid_key () {
msg -bar2 && msg -verm "  Code Invalid -- #¡Key Invalid#! " && msg -bar2
[[ -e $HOME/lista-arq ]] && rm -r $HOME/lista-arq
exit 1
}
while [[ ! $Key ]]; do
clear
clear
msg -bar
msg -tit
echo -e "\033[1;91m		\e[3;100mSCRIPT UPDATE \e[0m"
msg -bar2 && msg -ne "\033[1;93m          >>> ENTER THE KEY BELOW <<<\n   \033[1;37m" && read Key
tput cuu1 && tput dl1
done
msg -ne "    # Verificando Key # : "
cd $HOME
wget -O $HOME/lista-arq $(ofus "$Key")/$IP > /dev/null 2>&1 && echo -e "\033[1;32m Correct KEY Code" || {
   echo -e "\033[1;91m Incorrect KEY Code"
   invalid_key
   exit
   }
IP=$(ofus "$Key" | grep -vE '127\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | grep -o -E '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}') && echo "$IP" > /usr/bin/vendor_code
sleep 0.1s

function_verify
updatedb


if [[ -e $HOME/lista-arq ]] && [[ ! $(cat $HOME/lista-arq|grep "Invalid KEY Code!") ]]; then
   msg -bar2
   msg -verd "    $(source trans -b es:es "Ficheros Copiados"|sed -e 's/[^a-z -]//ig'): \e[97m[\e[93mSCRIPT MOD @conectedmx_bot\e[97m]"
   REQUEST=$(ofus "$Key"|cut -d'/' -f2)
   [[ ! -d ${SCPinstal} ]] && mkdir ${SCPinstal}
   pontos="." 
   stopping="Configurando Directorios"
   for arqx in $(cat $HOME/lista-arq); do
   msg -verm "${stopping}${pontos}" 
   wget --no-check-certificate -O ${SCPinstal}/${arqx} ${IP}:81/${REQUEST}/${arqx} > /dev/null 2>&1 && verificar_arq "${arqx}" || error_fun
   tput cuu1 && tput dl1
   pontos+="."
   done
userid="${SCPdir}/ID"
if [[ $(cat ${userid}|grep "605531451") = "" ]]; then
			activ=$(cat ${userid})
 		 TOKEN="1235413737:AAEWLffj1FO4GQ5Iwoo4XvIm4ESlFjHA0_A"
			URL="https://api.telegram.org/bot$TOKEN/sendMessage"
			MSG="👇= UPDATED SCRIPT =👇    
 ◄══════◄••◩••►══════►
 Version: $(cat /etc/versin_script_new) INSTALLED
 Cliente: $(cat ${SCPdir}/tmp/name)
 🆔: $(cat ${userid})
 Slogan: $(cat ${SCPdir}/message.txt)
 ◄══════◄••◩••►══════►
 IP: $(cat ${SCPdir}/MEUIPvps)
 ◄══════◄••◩••►══════►
 KEY:[ $Key ] Usada
 ◄══════◄••◩••►══════►
 ==NOTIFICADOR DE KEY==
 ◄══════◄••◩••►══════►
"
curl -s --max-time 10 -d "chat_id=$activ&disable_web_page_preview=1&text=$MSG" $URL &>/dev/null
curl -s --max-time 10 -d "chat_id=605531451&disable_web_page_preview=1&text=$MSG" $URL &>/dev/null
else
TOKEN="1235413737:AAEWLffj1FO4GQ5Iwoo4XvIm4ESlFjHA0_A"
			URL="https://api.telegram.org/bot$TOKEN/sendMessage"
			MSG="👇= UPDATED SCRIPT =👇    
◄══════◄••◩••►══════►
 Version: $(cat /etc/versin_script_new) INSTALLED
 Cliente: $(cat ${SCPdir}/tmp/name)
 🆔: $(cat ${userid})
 Slogan: $(cat ${SCPdir}/message.txt)
 ◄══════◄••◩••►══════►
 IP: $(cat ${SCPdir}/MEUIPvps)
 ◄══════◄••◩••►══════►
 KEY:[ $Key ] Usada
 ◄══════◄••◩••►══════►
 ==NOTIFICADOR DE KEY==
 ◄══════◄••◩••►══════►
"
curl -s --max-time 10 -d "chat_id=605531451&disable_web_page_preview=1&text=$MSG" $URL &>/dev/null
fi

	[[ ! -d ${SCPdir}/tmp ]] && mkdir ${SCPdir}/tmp
   wget -O ${SCPdir}/tmp/verifi https://www.dropbox.com/s/tv7yis89au5v8sv/verifi &>/dev/null
   wget -O ${SCPdir}/tmp/monitor https://www.dropbox.com/s/zwqhu7gavru6l9i/monitor &>/dev/null
   wget -O ${SCPdir}/tmp/autodes https://www.dropbox.com/s/fwcor9tbksnyuxy/autodes &>/dev/null
   wget -O /etc/VPS-MX/tmp/style https://www.dropbox.com/s/f33mi30lbxawvku/style &>/dev/null
   chmod 777 ${SCPdir}/*
 #  wget -O /etc/VPS-MX/protocolos/ssl5.sh https://www.dropbox.com/s/aly73lbbh74r7tu/ssl5.sh &>/dev/null
   #chmod 777 /etc/VPS-MX/protocolos/ssl5.sh
   wget -O /etc/VPS-MX/protocolos/chekuser.sh https://www.dropbox.com/s/dypjomdhjhkpahk/chekuser.sh &>/dev/null
   chmod 777 /etc/VPS-MX/protocolos/chekuser.sh
   wget -O /etc/VPS-MX/protocolos/chekuser.py https://www.dropbox.com/s/7he83qd5pfznrvh/chekuser.py &>/dev/null
   chmod 777 /etc/VPS-MX/protocolos/chekuser.py
   msg -bar2
   listaarqs="$(locate "lista-arq"|head -1)" && [[ -e ${listaarqs} ]] && rm $listaarqs   
   cat /etc/bash.bashrc|grep -v '[[ $UID != 0 ]] && TMOUT=15 && export TMOUT' > /etc/bash.bashrc.2
   echo -e '[[ $UID != 0 ]] && TMOUT=15 && export TMOUT' >> /etc/bash.bashrc.2
   mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
   echo "${SCPdir}/menu" > /usr/bin/menu && chmod +x /usr/bin/menu
   echo "${SCPdir}/menu" > /usr/bin/VPSMX && chmod +x /usr/bin/VPSMX
   echo "$Key" > ${SCPdir}/key.txt
   [[ -d ${SCPinstal} ]] && rm -rf ${SCPinstal}
   export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games/
	rm -rf /root/lista-arq
	[[ ! -e /etc/autostart ]] && {
	echo '#!/bin/bash
clear
#AUTOMATIC START' >/etc/autostart
	chmod +x /etc/autostart
} || {
	#[[ $(ps x | grep "bot_plus" | grep -v grep | wc -l) != '0' ]] && wget -qO- https://raw.githubusercontent.com/carecagm/main/Install/ShellBot.sh >/etc/SSHPlus/ShellBot.sh
	for proc in $(ps x | grep 'dmS' | grep -v 'grep' | awk {'print $1'}); do
		screen -r -S "$proc" -X quit
	done
	screen -wipe >/dev/null
	echo '#!/bin/bash
clear
#AUTOMATIC START' >/etc/autostart
	chmod +x /etc/autostart
}
crontab -r >/dev/null 2>&1
(
	crontab -l 2>/dev/null
	echo "@reboot /etc/autostart"
	echo "* * * * * /etc/autostart"
) | crontab -
   [[ ${#id} -gt 2 ]] && echo "es" > ${SCPidioma} || echo "es" > ${SCPidioma}
   echo -e "${cor[2]}               FULL UPDATE "
   echo -e "         MAIN COMMAND TO ENTER THE PANEL "
   echo -e "  \033[1;37m               sudo menu             \033[0;37m" && msg -bar2
rm -rf $HOME/lista-arq
else
invalid_key
fi
exit 1
}
funcao_idioma () {
tput cuu1 && tput dl1
msg -bar2
declare -A idioma=( [1]="en English" [2]="fr Franch" [3]="de German" [4]="it Italian" [5]="pl Polish" [6]="pt Portuguese" [7]="es Spanish" [8]="tr Turkish" )
for ((i=1; i<=12; i++)); do
valor1="$(echo ${idioma[$i]}|cut -d' ' -f2)"
[[ -z $valor1 ]] && break
valor1="\033[1;32m[$i] > \033[1;33m$valor1"
    while [[ ${#valor1} -lt 37 ]]; do
       valor1=$valor1" "
    done
echo -ne "$valor1"
let i++
valor2="$(echo ${idioma[$i]}|cut -d' ' -f2)"
[[ -z $valor2 ]] && {
   echo -e " "
   break
   }
valor2="\033[1;32m[$i] > \033[1;33m$valor2"
     while [[ ${#valor2} -lt 37 ]]; do
        valor2=$valor2" "
     done
echo -ne "$valor2"
let i++
valor3="$(echo ${idioma[$i]}|cut -d' ' -f2)"
[[ -z $valor3 ]] && {
   echo -e " "
   break
   }
valor3="\033[1;32m[$i] > \033[1;33m$valor3"
     while [[ ${#valor3} -lt 37 ]]; do
        valor3=$valor3" "
     done
echo -e "$valor3"
done
msg -bar2
unset selection
while [[ ${selection} != @([1-8]) ]]; do
echo -ne "\033[1;37m$(fun_trans "  ► Select an Option"): " && read selection
tput cuu1 && tput dl1
done
[[ -e /etc/VPS-MX/texto-mx ]] && rm /etc/VPS-MX/texto-mx
echo "$(echo ${idioma[$selection]}|cut -d' ' -f1)" > ${SCPidioma}
}


 menu_info () {
meu_ip &>/dev/null
#export -f fun_ip
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi

#_ram=$(printf '%-10s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_ram=$(printf ' %-8s' "$(free -h | grep -i mem | awk {'print $2'})")
_ram2=$(printf ' %-8s' "$(free -h | grep -i mem | awk {'print $4'})")
_system=$(printf '%-9s' "$system")
#_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
#_core=$(printf '%-8s' "$(grep -c cpu[0-9] /proc/stat)")
_core=$(printf '%-8s' "$(grep -c cpu[0-9] /proc/stat)")
_usop=$(top -bn1 | sed -rn '3s/[^0-9]* ([0-9\.]+) .*/\1/p;4s/.*, ([0-9]+) .*/\1/p' | tr '\n' ' ')

modelo1=$(printf '%-11s' "$(lscpu | grep Arch | sed 's/\s\+/,/g' | cut -d , -f2)")
mb=$(printf '%-8s' "$(free -h | grep Mem | sed 's/\s\+/,/g' | cut -d , -f6)")
_hora=$(printf '%(%H:%M:%S)T')
_hoje=$(date +'%d/%m/%Y')

echo -e "\033[1;37m OS \033[1;31m: \033[1;32m$_system \033[1;37mHORA\033[1;31m: \033[1;32m$_hora  \033[1;37mIP\033[1;31m:\033[1;32m $(meu_ip)"
echo -e "\033[1;37m RAM\e[31m: \033[1;32m$_ram \033[1;37mUSADO\033[1;31m: \033[1;32m$mb\033[1;37m LIBRE\033[1;31m: \033[1;32m$_ram2"

}


ofus () {
unset txtofus
number=$(expr length $1)
for((i=1; i<$number+1; i++)); do
txt[$i]=$(echo "$1" | cut -b $i)
case ${txt[$i]} in
".")txt[$i]="C";;
"C")txt[$i]=".";;
"3")txt[$i]="@";;
"@")txt[$i]="3";;
"5")txt[$i]="9";;
"9")txt[$i]="5";;
"6")txt[$i]="D";;
"D")txt[$i]="6";;
"J")txt[$i]="Z";;
"Z")txt[$i]="J";;
esac
txtofus+="${txt[$i]}"
done
echo "$txtofus" | rev
}
SPR &
limpar_caches () {
(
VE="\033[1;33m" && MA="\033[1;31m" && DE="\033[1;32m"
while [[ ! -e /tmp/abc ]]; do
A+="#"
echo -e "${VE}[${MA}${A}${VE}]" >&2
sleep 0.3s
tput cuu1 && tput dl1
done
echo -e "${VE}[${MA}${A}${VE}] - ${DE}[100%]" >&2
rm /tmp/abc
) &
echo 3 > /proc/sys/vm/drop_caches &>/dev/null
sleep 1s
sysctl -w vm.drop_caches=3 &>/dev/null
apt-get autoclean -y &>/dev/null
sleep 1s
apt-get clean -y &>/dev/null
rm /tmp/* &>/dev/null
touch /tmp/abc
sleep 0.5s
msg -bar
msg -ama "$(fun_trans "COMPLETED PROCESS")"
msg -bar
}
                                																								[[ ! -d cd ]] && exit
fun_autorun () {
if [[ -e /etc/bash.bashrc-bakup ]]; then
mv -f /etc/bash.bashrc-bakup /etc/bash.bashrc
cat /etc/bash.bashrc | grep -v "/etc/VPS-MX/menu" > /tmp/bash
mv -f /tmp/bash /etc/bash.bashrc
msg -ama "$(fun_trans "SUCCESSFULLY REMOVED")"
msg -bar
elif [[ -e /etc/bash.bashrc ]]; then
cat /etc/bash.bashrc|grep -v /bin/menu > /etc/bash.bashrc.2
echo '/etc/VPS-MX/menu' >> /etc/bash.bashrc.2
cp /etc/bash.bashrc /etc/bash.bashrc-bakup
mv -f /etc/bash.bashrc.2 /etc/bash.bashrc
msg -ama "$(fun_trans "AUTO INITIALIZE ADDED")"
msg -bar
fi
}
fun_bar () {
comando="$1"
 _=$(
$comando > /dev/null 2>&1
) & > /dev/null
pid=$!
while [[ -d /proc/$pid ]]; do
echo -ne " \033[1;33m["
   for((i=0; i<10; i++)); do
   echo -ne "\033[1;31m##"
   sleep 0.2
   done
echo -ne "\033[1;33m]"
sleep 1s
echo
tput cuu1
tput dl1
done
echo -e " \033[1;33m[\033[1;31m####################\033[1;33m] - \033[1;32m100%\033[0m"
sleep 1s
}

meu_ip () {
if [[ -e /etc/VPS-MX/MEUIPvps ]]; then
echo "$(cat /etc/VPS-MX/MEUIPvps)"
else
MEU_IP=$(wget -qO- ifconfig.me)
echo "$MEU_IP" > /etc/VPS-MX/MEUIPvps
fi
}
fun_ip () {
if [[ -e /etc/VPS-MX/MEUIPvps ]]; then
IP="$(cat /etc/VPS-MX/MEUIPvps)"
else
MEU_IP=$(wget -qO- ifconfig.me)
echo "$MEU_IP" > /etc/VPS-MX/MEUIPvps
fi
}

fun_eth () {
eth=$(ifconfig | grep -v inet6 | grep -v lo | grep -v 127.0.0.1 | grep "encap:Ethernet" | awk '{print $1}')
    [[ $eth != "" ]] && {
    msg -bar
    msg -ama " $(fun_trans "Apply system to improve SSH packets?")"
    msg -ama " $(fun_trans "Options for advanced users")"
    msg -bar
    read -p " [S/N]: " -e -i n sshsn
           [[ "$sshsn" = @(s|S|y|Y) ]] && {
           echo -e "${cor[1]} $(fun_trans "Correction of problems of packages in SSH ...")"
           echo -e " $(fun_trans "¿What is the RX rate?")"
           echo -ne "[ 1 - 999999999 ]: "; read rx
           [[ "$rx" = "" ]] && rx="999999999"
           echo -e " $(fun_trans "¿Cual es la tasa TX?")"
           echo -ne "[ 1 - 999999999 ]: "; read tx
           [[ "$tx" = "" ]] && tx="999999999"
           apt-get install ethtool -y > /dev/null 2>&1
           ethtool -G $eth rx $rx tx $tx > /dev/null 2>&1
           }
     msg -bar
     }
}
os_system () {
system=$(echo $(cat -n /etc/issue |grep 1 |cut -d' ' -f6,7,8 |sed 's/1//' |sed 's/      //'))
echo $system|awk '{print $1, $2}'
}
lacasita(){
unset puertos
	declare -A port
	local portasVAR=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN")
	#local portasVAR=$(lsof -V -i tcp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND" | grep "LISTEN" | grep -v 'systemd-resolve')
	local NOREPEAT
	local reQ
	local Port
	while read port; do
		reQ=$(echo ${port}|awk '{print $1}')
		Port=$(echo ${port} | awk '{print $9}' | awk -F ":" '{print $2}')
		[[ $(echo -e $NOREPEAT|grep -w "$Port") ]] && continue
		NOREPEAT+="$Port\n"
		case ${reQ} in
			squid|squid3)
			[[ -z ${port[SQD]} ]] && local port[SQD]="\033[1;31m SQUID: \033[1;32m"
			port[SQD]+="$Port ";;
			systemd-r|systemd-re|systemd-resolv)
			[[ -z ${port[md]} ]] && local port[md]="\033[1;31m SYSTEMD: \033[1;32m"
			port[md]+="$Port ";;
			apache|apache2)
			[[ -z ${port[APC]} ]] && local port[APC]="\033[1;31m APACHE: \033[1;32m"
			port[APC]+="$Port ";;
			nginx)
			[[ -z ${port[NG]} ]] && local port[NG]="\033[1;31m NGINX: \033[1;32m"
			port[NG]+="$Port ";;
			ssh|sshd)
			[[ -z ${port[SSH]} ]] && local port[SSH]="\033[1;31m SSH: \033[1;32m"
			port[SSH]+="$Port ";;
			dropbear)
			[[ -z ${port[DPB]} ]] && local port[DPB]="\033[1;31m DROPBEAR: \033[1;32m"
			port[DPB]+="$Port ";;
			ssserver|ss-server)
			[[ -z ${port[SSV]} ]] && local port[SSV]="\033[1;31m SHADOWSOCKS: \033[1;32m"
			port[SSV]+="$Port ";;
			obfs-serv)
			[[ -z ${port[OB]} ]] && local port[OB]="\033[1;31m OBFS: \033[1;32m"
			port[OB]+="$Port ";;
			trojan-go)
			[[ -z ${port[GO]} ]] && local port[GO]="\033[1;31m TROJAN GO: \033[1;32m"
			port[GO]+="$Port ";;
			trojan)
			[[ -z ${port[tro]} ]] && local port[tro]="\033[1;31m TROJAN: \033[1;32m"
			port[tro]+="$Port ";;
			openvpn)
			[[ -z ${port[OVPN]} ]] && local port[OVPN]="\033[1;31m OPENVPN-TCP: \033[1;32m"
			port[OVPN]+="$Port ";;
			stunnel4|stunnel)
			[[ -z ${port[SSL]} ]] && local port[SSL]="\033[1;31m SSL: \033[1;32m"
			port[SSL]+="$Port ";;
			stunnel5)
			[[ -z ${port[SSL5]} ]] && local port[SSL5]="\033[1;31m STUNNEL5: \033[1;32m"
			port[SSL5]+="$Port ";;
			python|python3)
			[[ -z ${port[PY3]} ]] && local port[PY3]="\033[1;31m PYTHON: \033[1;32m"
			port[PY3]+="$Port ";;
			node)
			[[ -z ${port[WS]} ]] && local port[WS]="\033[1;31m WEBSOCKET: \033[1;32m"
			port[WS]+="$Port ";;
			v2ray)
			[[ -z ${port[V2R]} ]] && local port[V2R]="\033[1;31m V2RAY: \033[1;32m"
			port[V2R]+="$Port ";;
			badvpn-ud)
			[[ -z ${port[BAD]} ]] && local port[BAD]="\033[1;31m BADVPN: \033[1;32m"
			port[BAD]+="$Port ";;
			
		esac
	done <<< "${portasVAR}"

	#UDP
	local portasVAR=$(lsof -V -i udp -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND")
	local NOREPEAT
	local reQ
	local Port
	while read port; do
		reQ=$(echo ${port}|awk '{print $1}')
		Port=$(echo ${port} | awk '{print $9}' | awk -F ":" '{print $2}')
		[[ $(echo -e $NOREPEAT|grep -w "$Port") ]] && continue
		NOREPEAT+="$Port\n"
		case ${reQ} in
			openvpn)
			[[ -z ${port[OVPN]} ]] && local port[OVPN]="\033[1;31m OPENVPN-UDP: \033[1;32m"
			port[OVPN]+="$Port ";;
			dns-serve)
			[[ -z ${port[SLOW]} ]] && local port[SLOW]="\033[1;31m SlowDNS: \033[1;32m"
			port[SLOW]+="$Port ";;
			#stunnel5)
			#[[ -z ${port[SSL]} ]] && local port[SSL]="\033[1;31m SSL: \033[1;32m"
			#port[SSL]+="$Port ";;
		esac
	done <<< "${portasVAR}"
[[ $(dpkg --get-selections|grep -w 'wireguard'|head -1) ]] && {
		if [[ ! $(wg|grep -w 'interface') = "" ]]; then
			wg=$(wg|grep -w 'port'|awk -F ' ' '{print $3}')
			port[wg]="\033[1;31m WIREGUARD:\033[1;32m $wg"
		fi
	}
	k=1

	for line in "${port[@]}"; do
		[[ -z "$line" ]] && continue
		let RESTO=k%2

		if [[ $RESTO -eq 0 ]]; then
			puertos+="$line\n"
		else
			puertos+="$line-"
		fi
		let k++

	done

	echo -e "$puertos"|column -t -s '-'
	}
	
remove_script () {
clear
clear 
#msg -bar
msg -tit
msg -ama "          ¿ WANT TO UNINSTALL SCRIPT ?"
msg -bar
echo -e " Esto borrara todos los archivos del scrip VPS_MX"
msg -bar
while [[ ${yesno} != @(s|S|y|Y|n|N) ]]; do
read -p " [S/N]: " yesno
tput cuu1 && tput dl1
done
if [[ ${yesno} = @(s|S|y|Y) ]]; then
rm -rf ${SCPdir} &>/dev/null
rm -rf ${SCPusr} &>/dev/null
rm -rf ${SCPinst} &>/dev/null
[[ ! -d /usr/local/lib/ubuntn ]] && rm -rf /usr/local/lib/ubuntn
[[ ! -d /usr/share/mediaptre/local/log ]] && rm -rf /usr/share/mediaptre/local/log
[[ ! -d /usr/local/protec ]] && rm -rf /usr/local/protec
[[ -e /bin/VPSMX ]] && rm /bin/VPSMX
[[ -e /usr/bin/VPSMX ]] && rm /usr/bin/VPSMX
[[ -e /bin/menu ]] && rm /bin/menu
[[ -e /usr/bin/menu ]] && rm /usr/bin/menu
cd $HOME
fi
sudo apt-get --purge remove squid -y > /dev/null 2>&1
sudo apt-get --purge remove stunnel4 -y > /dev/null 2>&1
sudo apt-get --purge remove dropbear -y > /dev/null 2>&1
sudo apt-get autoremove -y &>/dev/null
}
horas(){
#code by rufu99
msg -bar
echo -e "	\e[41mUPDATE LOCAL TIME\e[0m"
msg -bar
	n=1
    for i in $(ls /usr/share/zoneinfo/America); do
        loc=$(echo $i|awk -F ":" '{print $1}')
        zona=$(printf '%-12s' "$loc")
        echo -e " \e[37m [$n] \e[31m> \e[32m$zona"
        r[$n]=$zona
        selec="$n"
        let n++ 
    done
   msg -bar
    opci=$(selection_fun $selec)
  rm -rf /etc/localtime > /dev/null 2>&1
  echo "America/${r[$opci]}" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/${r[$opci]} /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1 && echo -e "\033[1;32m [UPDATED TIME]" || echo -e "\033[1;31m [TIME NOT UPDATED]"
#fin
#
}
onlineapp(){
msg -bar
echo -e "\033[1;92m                ACTIVATING SERVICE"
msg -bar
wget -O /etc/VPS-MX/herramientas/.onapp https://www.dropbox.com/s/z0xb6pbe1uagdjt/onapp &>/dev/null
chmod 777 /etc/VPS-MX/herramientas/.onapp &>/dev/null
   apt install apache2 -y > /dev/null 2>&1
   sed -i "s/Listen 81/Listen 8888/g" /etc/apache2/ports.conf >/dev/null 2>&1
   service apache2 restart
   rm -rf /var/www/html/server >/dev/null 2>&1
   mkdir /var/www/html/server >/dev/null 2>&1
echo -e "[Unit]
Description=.onapp Service by @lacasitamx
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=root
WorkingDirectory=/root
ExecStart=/bin/bash /etc/VPS-MX/herramientas/.onapp
Restart=always
RestartSec=3s

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/app.service

    systemctl enable app &>/dev/null
    systemctl start app &>/dev/null
    IP=$(wget -qO- ipv4.icanhazip.com) >/dev/null 2>&1
msg -bar
echo -e "\033[1;92m                ONLINE APP STARTED SUCCESSFULLY"
msg -bar
echo -e "\033[1;37m Online users URL to use in the app‌‌\033[0m"
   echo -e "\e[1;92m http://$IP:8888/server/online"
   msg -bar
}
killapp(){
	systemctl stop app &>/dev/null
    systemctl disable app  &>/dev/null
    rm /etc/systemd/system/app.service &>/dev/null
    rm -rf /var/www/html/server >/dev/null 2>&1
    sed -i "s/Listen 8888/Listen 81/g" /etc/apache2/ports.conf >/dev/null 2>&1
   service apache2 restart
    msg -bar
    echo -e "\033[1;91m                ONLINE APP STOPPED"
msg -bar

}
menuapp(){
clear
msg -tit
msg -azu "	\e[91m\e[43mACTIVATE APP ONLINE\e[0m"
msg -bar
echo -e " \e[1;93m [\e[92m1\e[93m] $(msg -verm2 "➛ ")$(msg -verd "  START APP ONLINE  ")"
echo -e " \e[1;93m [\e[92m2\e[93m] $(msg -verm2 "➛ ")$(msg -verm2 " STOP ONLINE APP   ")"
echo -e " \e[1;93m [\e[92m0\e[93m] $(msg -verm2 "➛ ")$(msg -bra "  RETURN   ")"
msg -bar
echo -ne " ►\e[1;37m Select An Option: \e[33m " && read select
case $select in
0)menu3 ;;
1) onlineapp && msg -ne "Enter to continue" && read enter
menu3 ;;
2)killapp && msg -ne "Enter to continue" && read enter
menu3 ;;
esac
}

systen_info () {
clear
clear
#msg -bar
msg -tit
msg -ama "$(fun_trans "                SYSTEM DETAILS")"
null="\033[1;31m"
msg -bar
if [ ! /proc/cpuinfo ]; then msg -verm "$(fun_trans "System Not Supported")" && msg -bar; return 1; fi
if [ ! /etc/issue.net ]; then msg -verm "$(fun_trans "System Not Supported")" && msg -bar; return 1; fi
if [ ! /proc/meminfo ]; then msg -verm "$(fun_trans "System Not Supported")" && msg -bar; return 1; fi
totalram=$(free | grep Mem | awk '{print $2}')
usedram=$(free | grep Mem | awk '{print $3}')
freeram=$(free | grep Mem | awk '{print $4}')
swapram=$(cat /proc/meminfo | grep SwapTotal | awk '{print $2}')
system=$(cat /etc/issue.net)
clock=$(lscpu | grep "CPU MHz" | awk '{print $3}')
based=$(cat /etc/*release | grep ID_LIKE | awk -F "=" '{print $2}')
processor=$(cat /proc/cpuinfo | grep "model name" | uniq | awk -F ":" '{print $2}')
cpus=$(cat /proc/cpuinfo | grep processor | wc -l)
[[ "$system" ]] && msg -ama "$(fun_trans "System"): ${null}$system" || msg -ama "$(fun_trans "System"): ${null}???"
[[ "$based" ]] && msg -ama "$(fun_trans "Base"): ${null}$based" || msg -ama "$(fun_trans "Base"): ${null}???"
[[ "$processor" ]] && msg -ama "$(fun_trans "Processor"): ${null}$processor x$cpus" || msg -ama "$(fun_trans "Processor"): ${null}???"
[[ "$clock" ]] && msg -ama "$(fun_trans "Operating Frequencyn"): ${null}$clock MHz" || msg -ama "$(fun_trans "Operating Frequency"): ${null}???"
msg -ama "$(fun_trans "Uso del Procesador"): ${null}$(ps aux  | awk 'BEGIN { sum = 0 }  { sum += sprintf("%f",$3) }; END { printf " " "%.2f" "%%", sum}')"
msg -ama "$(fun_trans "Memoria Virtual Total"): ${null}$(($totalram / 1024))"
msg -ama "$(fun_trans "Memoria Virtual En Uso"): ${null}$(($usedram / 1024))"
msg -ama "$(fun_trans "Memoria Virtual Libre"): ${null}$(($freeram / 1024))"
msg -ama "$(fun_trans "Memoria Virtual Swap"): ${null}$(($swapram / 1024))MB"
msg -ama "$(fun_trans "Tempo Online"): ${null}$(uptime)"
msg -ama "$(fun_trans "Nombre De La Maquina"): ${null}$(hostname)"
msg -ama "$(fun_trans "IP De La  Maquina"): ${null}$(ip addr | grep inet | grep -v inet6 | grep -v "host lo" | awk '{print $2}' | awk -F "/" '{print $1}')"
msg -ama "$(fun_trans "Version de Kernel"): ${null}$(uname -r)"
msg -ama "$(fun_trans "Arquitectura"): ${null}$(uname -m)"
msg -bar
return 0
}
	[[ "$(crontab -l| grep 'autolim' | wc -l)" != '0' ]] &>/dev/null && {
  autram="\e[1;32m[ON]"
  } || {
  autram="\e[1;31m[OFF]"
  }
  
menu3(){
declare -A inst
pidr_inst
clear
valuest=$(ps ax |grep /etc/shadowsocks-r|grep -v grep)
[[ $valuest != "" ]] && valuest="\033[1;32m[ON] " || valuest="\033[1;31m[OFF]"
pidproxy=$(ps x | grep -w  "lacasitamx.py" | grep -v "grep" | awk -F "pts" '{print $1}') && [[ ! -z $pidproxy ]] && plox="\e[1;32m[ON] " || plox="\e[1;31m[OFF]"
Bot=$(ps x|grep -v grep |grep "ADMbot.sh")
[[ ! $Bot ]] && AD="\033[1;31m[OFF]" || AD="\033[1;32m[ON] "
#[[ $(ps x | grep stunnel5 | grep -v grep | awk '{print $1}') ]] && stunel5="\e[1;32m[ON]" || stunel5="\e[1;31m[OFF]"
#msg -bar
msg -tit
export -f fun_eth
export -f fun_bar
#echo -e "\e[1;37mTotal Ram: ${null}$(($totalram / 1024)) \e[1;37mUSO: ${null}$(($usedram / 1024)) \e[1;37mLIBRE: ${null}$(($freeram / 1024)) \e[37mSwap:${null}$(($swapram / 1024))MB"
export -f lacasita
lacasita
	msg -bar
echo -e "  	\e[97m\e[1;100mPROTOCOLOS\e[0m  		  \e[97m\e[41mHERRAMIENTAS\e[0m"
msg -bar
 if [[ ! -e /etc/noty ]]; then
 noty="\e[1;91m[OFF]"
 else
 noty="\e[1;92m[ON] "
 fi
 onap=$(ps x|grep -v grep |grep ".onapp")
[[ ! $onap ]] && app="\033[1;31m[OFF]" || app="\033[1;32m[ON] "
 if [[ $(systemctl is-active chekuser) = "active" ]]; then
 chek="\e[1;92m[ON] "
 else
 chek="\e[1;91m[OFF]"
 fi
#menu de protocolos
echo -e "\e[1;93m[\e[92m1\e[93m]$(msg -verm2 "➛ ")$(msg -azu "BADVPN        ${inst[badvpn]}")  \e[1;93m[\e[92m15\e[93m]$(msg -verm2 "➛ ")$(msg -azu "ONLINE ARCHIVE")"
echo -e "\e[1;93m[\e[92m2\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SOCKS LIBEV   ${inst[ss-server]}")  \e[1;93m[\e[92m16\e[93m]$(msg -verm2 "➛ ")$(msg -azu "FIREWALL")"
echo -e "\e[1;93m[\e[92m3\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SOCKS PYTHON  ${inst[python]}")  \e[1;93m[\e[92m17\e[93m]$(msg -verm2 "➛ ")$(msg -azu "FAIL2BAN PROTECION")"
echo -e "\e[1;93m[\e[92m4\e[93m]$(msg -verm2 "➛ ")$(msg -azu "V2RAY         ${inst[v2ray]}")  \e[1;93m[\e[92m18\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SYSTEM DETAILS")"
echo -e "\e[1;93m[\e[92m5\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SSL           ${inst[stunnel4]}")  \e[1;93m[\e[92m19\e[93m]$(msg -verm2 "➛ ")$(msg -azu "TCP (BBR|BBR-Plus)")"
echo -e "\e[1;93m[\e[92m6\e[93m]$(msg -verm2 "➛ ")$(msg -azu "DROPBEAR      ${inst[dropbear]}")  \e[1;93m[\e[92m20\e[93m]$(msg -verm2 "➛ ")$(msg -azu "DNS NETFLIX")"
echo -e "\e[1;93m[\e[92m7\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SQUID         ${inst[squid]}")  \e[1;93m[\e[92m21\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SELF MAINTENANCE")$autram"
echo -e "\e[1;93m[\e[92m8\e[93m]$(msg -verm2 "➛ ")$(msg -azu "OPENVPN       ${inst[openvpn]}")  \e[1;93m[\e[92m22\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SCANNER SUBDOMINIO")"
echo -e "\e[1;93m[\e[92m9\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SLOWDNS       ${inst[dns-serve]}")  \e[1;93m[\e[92m23\e[93m]$(msg -verm2 "➛ ")$(msg -azu "SPEED TEST")"
echo -e "\e[1;93m[\e[92m10\e[93m]$(msg -verm2 "➛ ")$(msg -azu "MONITOR APP  $app")  \e[1;93m[\e[92m24\e[93m]$(msg -verm2 "➛ ")$(msg -azu "FIX ORACLE/AWS/AZR")"
echo -e "\e[1;93m[\e[92m11\e[93m]$(msg -verm2 "➛ ")$(msg -azu "BOT TELEGRAM $AD")  \e[1;93m[\e[92m25\e[93m]$(msg -verm2 "➛ ")$(msg -azu "\e[91m\e[43mBASIC TOOLS\e[0m")"
echo -e "\e[1;93m[\e[92m12\e[93m]$(msg -verm2 "➛ ")$(msg -azu "WIREGUARD    ${inst[wg]}")  $(msg -verd "[0] ")$(msg -verm2 "➛ ")$(msg -azu "⇚ VOLVER  ")" 
echo -e "\e[1;93m[\e[92m13\e[93m]$(msg -verm2 "➛ ")$(msg -azu "NOTI-BOT     $noty")"
echo -e "\e[1;93m[\e[92m14\e[93m]$(msg -verm2 "➛ ")$(msg -azu "CHECK-USER   $chek")"
msg -bar
echo -ne " ►\e[1;37m Select an option: \e[33m " && read select
case $select in
0) ;;
1) ${SCPinst}/budp.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
2) ${SCPinst}/shadowsocks.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
3) ${SCPinst}/sockspy.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
4) ${SCPinst}/v2ray.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
5) ${SCPinst}/ssl.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
6) ${SCPinst}/dropbear.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
7) ${SCPinst}/squid.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
8) ${SCPinst}/openvpn.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
9) ${SCPinst}/slowdns.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
#
#herramientas
10) menuapp && msg -ne "Enter to continue" && read enter
menu3 ;;
11) adminbot;;
12) ${SCPinst}/wireguard.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
13) noti ;;
14) ${SCPinst}/chekuser.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
15) ${SCPfrm}/apacheon.sh;;
16) ${SCPfrm}/blockBT.sh;;
17) ${SCPfrm}/fai2ban.sh;;
18) systen_info;;
19) ${SCPfrm}/tcp.sh;;
20) net;;
21) cache;;
22) ${SCPfrm}/ultrahost;;
23) ${SCPfrm}/speed.py;;
24)oracl ;;
25) extra ;;
#25)${SCPinst}/trojango.sh && msg -ne "Enter Para Continuar" && read enter
#menu3 ;;
*) msg -verm2 " Please Select The Correct Number"
sleep 1.s
menu3 ;;
esac
}
NOTIFY () {
clear
clear
msg -tit

msg -ama " Notify-BOT (Remote Notification)|@LaCasitaMx_Noty_Bot "
msg -bar
echo -e "\033[1;94m Notify-BOT is a simple notifier of:"
echo -e "\033[1;94m >> Expired User"
echo -e "\033[1;94m >> User Deleted"
echo -e "\033[1;94m >> Restarted VPS Warnings"
echo -e "\033[1;94m >> Protocol Monitor Notices"
echo -e "\033[1;97m Start The Telegram BOT"
echo -e "\033[1;92m ¡¡ To get their ID between to the BOT @conectedmx_bot"
echo -e "\033[1;92m Something similar will appear 👤 → Your ID is: 45145564  "
msg -bar
echo -e "\033[1;93mEnter a name for the VPS:\033[0;37m"; read -p " " nombr
echo "${nombr}" > /etc/VPS-MX/controlador/nombre.log
echo -e "\033[1;93mGames are ID 👤:\033[0;37m"; read -p " " idbot
echo "${idbot}" > /etc/VPS-MX/controlador/IDT.log 
msg -bar
echo -e "\033[1;32m              ID ADDED SUCCESSFULLY"
msg -bar
wget -qO- ifconfig.me > /etc/VPS-MX/IP.log
ipt=`less /etc/VPS-MX/IP.log` > /dev/null 2>&1
Nip="$(echo $ipt)"
NOM="$(less /etc/VPS-MX/controlador/nombre.log)"
NOM1="$(echo $NOM)"
IDB1=`less /etc/VPS-MX/controlador/IDT.log` > /dev/null 2>&1
IDB2=`echo $IDB1` > /dev/null 2>&1
KEY="2012880601:AAEJ3Kk18PGDzW57LpTMnVMn_pQYQKW3V9w"
URL="https://api.telegram.org/bot$KEY/sendMessage"
MSG="⚠️ ►► VPS WARNING: $NOM1 ⚠
👉 ►► IP: $Nip
👉 ►► User: $(cat /etc/VPS-MX/message.txt)
👉 ►► TEST MESSAGE
🔰 ►► NOTI-BOT ACTIVATED SUCCESSFULLY"
curl -s --max-time 10 -d "chat_id=$IDB2&disable_web_page_preview=1&text=$MSG" $URL &>/dev/null
echo -e "\033[1;34m            TEST MESSAGE SENT "
touch /etc/noty
}

noti(){
clear
msg -tit
echo -e "	\e[97m\e[1;100mNOTI-BOT ACTIVATOR\e[0m"
msg -bar
echo -e "\e[1;93m[\e[92m1\e[93m]$(msg -verm2 "➛ ")$(msg -azu "ACTIVATE NOTI-BOT $nt")  \e[1;93m[\e[92m2\e[93m]$(msg -verm2 "➛ ")$(msg -azu "DISABLE NOTI-BOT")"
msg -bar
echo -e "	     	\e[1;93m[\e[92m0\e[93m]$(msg -verm2 "➛ ")$(msg -azu "RETURN")"
msg -bar
echo -ne " ►\e[1;37m Select an option: \e[33m " && read selectos
case $selectos in
0)menu3 ;;
1) NOTIFY && msg -ne "Enter to continue" && read enter
menu3 ;;
2)
echo " "> /etc/VPS-MX/controlador/IDT.log &>/dev/null
rm /etc/noty &>/dev/null
msg -verm2 "	NOTI-BOT DISABLED"
;;
esac
}

adminbot(){
clear
#msg -bar
#msg -tit
echo ""
echo -e "\e[1;90m╔─━━━━━━━━━━━━━━░★░━━━━━━━━━━━━━━─╗                \e[0m"
msg -ama " ░ ADMINISTRATOR BOT | TELEGRAM ░                   \033[1;31m"
echo -e "\e[1;90m╚─━━━━━━━━━━━━━━░★░━━━━━━━━━━━━━━─╝                \e[0m"
activar(){
msg -bar
echo -ne "\033[1;96m #Digitize the BOT Token\033[0;92m\nTOKEN: \033[0;97m" && read TOKEN
msg -bar
echo -ne "\033[1;96m #Enter a name for your User\033[0;92m \nUSER: \033[0;97m" && read USERLIB
msg -bar
echo -ne "\033[1;96m #Enter a password for your User\033[0;92m \nPASSWORD: \033[0;97m" && read PASSLIB
#msg -bar
echo -e "[Unit]
Description=ADMbot.sh Service by @lacasitamx
After=network.target
StartLimitIntervalSec=0

[Service]
Type=simple
User=root
WorkingDirectory=/root
ExecStart=/bin/bash /etc/VPS-MX/herramientas/ADMbot.sh id "$TOKEN" "$USERLIB" "$PASSLIB"
Restart=always
RestartSec=3s

[Install]
WantedBy=multi-user.target" > /etc/systemd/system/Botca.service

    systemctl enable Botca &>/dev/null
    systemctl start Botca &>/dev/null
msg -bar
echo -e "\033[1;92m                BOT STARTED SUCCESSFULLY"
echo -e "\033[1;97m BOT START MODE: /ADMIN $USERLIB $PASSLIB"
msg -bar
}

killbot(){
	systemctl stop Botca &>/dev/null
    systemctl disable Botca  &>/dev/null
    rm /etc/systemd/system/Botca.service &>/dev/null
    msg -bar
    echo -e "\033[1;91m               BOT DETECTED"
msg -bar

}
echo -e " \e[1;93m[\e[92m1\e[93m] $(msg -verm2 "➛ ")$(msg -verd "  START BOT MANAGER   ")"
echo -e " \e[1;93m[\e[92m2\e[93m] $(msg -verm2 "➛ ")$(msg -verm2 " STOP BOT MANAGER   ")"
echo -e " \e[1;93m[\e[92m0\e[93m] $(msg -verm2 "➛ ")$(msg -bra "  RETURN   ")"
msg -bar
echo -ne " ►\e[1;37m Select an option: \e[33m " && read select
case $select in
0)menu3 ;;
1)activar && msg -ne "Enter to continue" && read enter
menu3 ;;
2)killbot && msg -ne "Enter to continue" && read enter
menu3 ;;
esac
}

extra(){
clear
clear
#msg -bar
msg -tit
on="\033[1;32m[ON]" && off="\033[1;31m[OFF]"
[[ `grep -c "^#ADM" /etc/sysctl.conf` -eq 0 ]] && tcp=$off || tcp=$on
if [ -e /etc/squid/squid.conf ]; then
[[ `grep -c "^#CACHE_DO_SQUID" /etc/squid/squid.conf` -gt 0 ]] && squi=$off || squi=$on
elif [ -e /etc/squid3/squid.conf ]; then
[[ `grep -c "^#CACHE_DO_SQUID" /etc/squid3/squid.conf` -gt 0 ]] && squi=$off || squi=$on
fi
echo -e "		\e[91m\e[43mBASIC TOOLS\e[0m"
msg -bar
echo -e " \e[1;93m[\e[92m1\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "UPDATE LOCAL TIME")"
echo -e " \e[1;93m[\e[92m2\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "HTOP")"
echo -e " \e[1;93m[\e[92m3\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "MODIFY ACTIVE PORTS")"
echo -e " \e[1;93m[\e[92m4\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "PAYLOAD BRUTE FORCE")"
echo -e " \e[1;93m[\e[92m5\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "TCP SPEED") $tcp"
echo -e " \e[1;93m[\e[92m6\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "CACHE FOR SQUID") $squi"
echo -e " \e[1;93m[\e[92m7\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "CLEAN OBSOLETE PACKAGES")"
echo -e " \e[1;93m[\e[92m8\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "RESET IPTABLES")"
echo -e " \e[1;93m[\e[92m9\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "RESTART VPS")"
echo -e " \e[1;93m[\e[92m10\e[93m]$(msg -verm2 "➛ ")$(msg -azu "CHANGE VPS HOSTNAME")"
echo -e " \e[1;93m[\e[92m11\e[93m]$(msg -verm2 "➛ ")$(msg -azu "CHANGE ROOT PASSWORD")"
echo -e " \e[1;93m[\e[92m12\e[93m]$(msg -verm2 "➛ ")$(msg -azu "ADD ROOT to GoogleCloud and Amazon")"
echo -e " \e[1;93m[\e[92m13\e[93m]$(msg -verm2 "➛ ")$(msg -azu "I will authenticate SQUID")"
echo -e " \e[1;93m[\e[92m0\e[93m]$(msg -verm2 " ➛ ")$(msg -azu "RETURN")"
msg -bar
echo -ne " ►\e[1;37m Select an option: \e[33m " && read select
case $select in
0)menu3 ;;
1)horas ;;
2)monhtop ;;
3)${SCPfrm}/ports.sh && msg -ne "Enter to continue" && read enter
menu3 ;;
4)${SCPfrm}/paysnd.sh ;;
5)TCPspeed ;;
6)SquidCACHE ;;
7)packobs ;;
8)resetiptables ;;
9)reiniciar_vps ;;
10)host_name ;;
11)cambiopass ;;
12)rootpass ;;
13)${SCPfrm}/squidpass.sh ;;
*) ;;
esac
}

reiniciar_vps () {
echo -ne " \033[1;31m[ ! ] Sudo Reboot"
sleep 3s
echo -e "\033[1;32m [OK]"
(
sudo reboot
) > /dev/null 2>&1
msg -bar
return
}

host_name () {
unset name
while [[ ${name} = "" ]]; do
echo -ne "\033[1;37m $(fun_trans "new hostname"): " && read name
tput cuu1 && tput dl1
done
hostnamectl set-hostname $name 
if [ $(hostnamectl status | head -1  | awk '{print $3}') = "${name}" ]; then 
echo -e "\033[1;33m $(fun_trans "Host changed correctly")!, $(fun_trans "restart VPS")"
else
echo -e "\033[1;33m $(fun_trans "Unmodified host")!"
fi
msg -bar
return
}

cambiopass () {
echo -e "${cor[3]} $(fun_trans "This tool changes the password of your vps server")"
echo -e "${cor[3]} $(fun_trans "This password is used as user") root"
msg -bar
echo -ne " $(fun_trans "Do you want to continue?") [S/N]: "; read x
[[ $x = @(n|N) ]] && msg -bar && return
msg -bar
#Inicia Procedimentos
echo -e "${cor[0]} $(fun_trans "Type your new password")"
msg -bar
read  -p " new password: " pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
msg -bar
echo -e "${cor[3]} $(fun_trans "Password changed successfully!")"
echo -e "${cor[2]} $(fun_trans "Your password is now"): ${cor[4]}$pass"
msg -bar
return
}
dnsnetflix () {
#by kalix1
echo "nameserver $dns1" >> /etc/resolv.conf
#echo "nameserver $dns2" >> /etc/resolv.conf
/etc/init.d/ssrmu stop &>/dev/null
/etc/init.d/ssrmu start &>/dev/null
/etc/init.d/shadowsocks-r stop &>/dev/null
/etc/init.d/shadowsocks-r start &>/dev/null
msg -bar2
echo -e "${cor[4]}  DNS SUCCESSFULLY ADDED"
}
net(){
#by kalix1
clear
#msg -bar2
msg -tit
echo -e "\033[1;93m     PERSONAL DNS AGGREGATOR"
msg -bar2
echo -e "\033[1;39m This function so you can watch Netflix with your VPS"
msg -bar2
#echo -e "\033[1;91m ¡ Solo seran utiles si registraste tu IP en el BOT !"
echo -e "\033[1;39m In APPS like HTTP Injector, KPN Rev, APKCUSTOM, etc.."
echo -e "\033[1;39m They should be added in the application to use these DNS."
echo -e "\033[1;39m In APPS like SS,SSR,V2RAY you don't need to add them."
msg -bar2
echo -e "\033[1;93m Remember to choose between 1 DNS either USA, BR, MX, CL \n as the BOT has given you."
echo ""
echo -e "\033[1;97m Enter your Primary DNS: \033[0;91m"; read -p " Primary Dns: "  dns1
echo -e "\033[1;97m Enter your Secondary DNS: \033[0;91m"; read -p " Secondary Dns: "  dns2
echo ""
msg -bar2
read -p " Are you sure to continue? [ s | n ]: " dnsnetflix   
[[ "$dnsnetflix" = "s" || "$dnsnetflix" = "S" ]] && dnsnetflix
msg -bar2
}
rootpass () {
clear
msg -bar
echo -e "${cor[3]}  This tool changes to root user the VPS of "
echo -e "${cor[3]}            GoogleCloud y Amazon"
msg -bar
echo -ne " Do you want to continue? [S/N]: "; read x
[[ $x = @(n|N) ]] && msg -bar && return
msg -bar
#Inicia Procedimentos
echo -e "                 Applying Settings"
fun_bar "service ssh restart"
#Parametros Aplicados
sed -i "s;PermitRootLogin prohibit-password;PermitRootLogin yes;g" /etc/ssh/sshd_config
sed -i "s;PermitRootLogin without-password;PermitRootLogin yes;g" /etc/ssh/sshd_config
sed -i "s;PasswordAuthentication no;PasswordAuthentication yes;g" /etc/ssh/sshd_config
msg -bar
echo -e "Type your current root password or change it"
msg -bar
read  -p " New password: " pass
(echo $pass; echo $pass)|passwd 2>/dev/null
sleep 1s
msg -bar
echo -e "${cor[3]} Settings applied successfully!"
echo -e "${cor[2]} Your password is now: ${cor[4]}$pass"
service ssh restart > /dev/null 2>&1
msg -bar
return
}

resetiptables () {
echo -e "Restarting Ipetables wait"
iptables -F && iptables -X && iptables -t nat -F && iptables -t nat -X && iptables -t mangle -F && iptables -t mangle -X && iptables -t raw -F && iptables -t raw -X && iptables -t security -F && iptables -t security -X && iptables -P INPUT ACCEPT && iptables -P FORWARD ACCEPT && iptables -P OUTPUT ACCEPT
echo -e "iptables restarted successfully"
}
packobs () {
msg -ama "Looking for Outdated Packages"
dpkg -l | grep -i ^rc
msg -ama "Cleaning Outdated Packages"
dpkg -l |grep -i ^rc | cut -d " " -f 3 | xargs dpkg --purge
msg -ama "Full wipe"
}

TCPspeed () {
if [[ `grep -c "^#ADM" /etc/sysctl.conf` -eq 0 ]]; then
#INSTALA
msg -ama "$(fun_trans "TCP Speed ​​Not Enabled, Want to Enable Now")?"
msg -bar
while [[ ${resposta} != @(s|S|n|N|y|Y) ]]; do
read -p " [S/N]: " -e -i s resposta
tput cuu1 && tput dl1
done
[[ "$resposta" = @(s|S|y|Y) ]] && {
echo "#ADM" >> /etc/sysctl.conf
echo "net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" >> /etc/sysctl.conf
sysctl -p /etc/sysctl.conf > /dev/null 2>&1
msg -ama "$(fun_trans "TCP Activo Con Exito")!"
} || msg -ama "$(fun_trans "Cancelado")!"
 else
#REMOVE
msg -ama "$(fun_trans "TCP Speed ​​is already enabled, you want to stop now")?"
msg -bar
while [[ ${resposta} != @(s|S|n|N|y|Y) ]]; do
read -p " [S/N]: " -e -i s resposta
tput cuu1 && tput dl1
done
[[ "$resposta" = @(s|S|y|Y) ]] && {
grep -v "^#ADM
net.ipv4.tcp_window_scaling = 1
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 16384 16777216
net.ipv4.tcp_low_latency = 1
net.ipv4.tcp_slow_start_after_idle = 0" /etc/sysctl.conf > /tmp/syscl && mv -f /tmp/syscl /etc/sysctl.conf
sysctl -p /etc/sysctl.conf > /dev/null 2>&1
msg -ama "$(fun_trans "TCP Stopped Successfully")!"
} || msg -ama "$(fun_trans "Canceled")!"
fi
}
SquidCACHE () {
msg -ama "$(fun_trans "Squid Cache, Apply cache in Squid")"
msg -ama "$(fun_trans "Improve squid speed")"
msg -bar
if [ -e /etc/squid/squid.conf ]; then
squid_var="/etc/squid/squid.conf"
elif [ -e /etc/squid3/squid.conf ]; then
squid_var="/etc/squid3/squid.conf"
else
msg -ama "$(fun_trans "Your system does not have a squid")!" && return 1
fi
teste_cache="#CACHE_DO_SQUID"
if [[ `grep -c "^$teste_cache" $squid_var` -gt 0 ]]; then
  [[ -e ${squid_var}.bakk ]] && {
  msg -ama "$(fun_trans "Cache squid identified, removing")!"
  mv -f ${squid_var}.bakk $squid_var
  msg -ama "$(fun_trans "Cache squid Removido")!"
  service squid restart > /dev/null 2>&1 &
  service squid3 restart > /dev/null 2>&1 &
  return 0
  }
fi
msg -ama "$(fun_trans "Applying Squid Cache")!"
msg -bar
_tmp="#CACHE_DO_SQUID\ncache_mem 200 MB\nmaximum_object_size_in_memory 32 KB\nmaximum_object_size 1024 MB\nminimum_object_size 0 KB\ncache_swap_low 90\ncache_swap_high 95"
[[ "$squid_var" = "/etc/squid/squid.conf" ]] && _tmp+="\ncache_dir ufs /var/spool/squid 100 16 256\naccess_log /var/log/squid/access.log squid" || _tmp+="\ncache_dir ufs /var/spool/squid3 100 16 256\naccess_log /var/log/squid3/access.log squid"
while read s_squid; do
[[ "$s_squid" != "cache deny all" ]] && _tmp+="\n${s_squid}"
done < $squid_var
cp ${squid_var} ${squid_var}.bakk
echo -e "${_tmp}" > $squid_var
msg -ama "$(fun_trans "Cache Applied Successfully")!"
service squid restart > /dev/null 2>&1 &
service squid3 restart > /dev/null 2>&1 &
}


oracl(){
clear
#msg -bar
msg -tit
msg -verm "		FIREWALLD"
msg -ama " THIS TOOL IS FOR ORACLE/AWS/AZR VPS"
msg -ama " ALSO FOR OTHER VPS THAT ARE NECESSARY TO USE THIS OPTION"
echo -ne " Do you wont to continue? [S/N]: "; read x
[[ $x = @(n|N) ]] && msg -bar && return
msg -bar
sudo apt update -y &>/dev/null
sudo apt install firewalld -y &>/dev/null
sudo apt install apache2 &>/dev/null
#sudo firewall-cmd --permanent --add-service={http,https} --permanent
sudo firewall-cmd --zone=public --permanent --add-port=80/tcp
sudo firewall-cmd --zone=public --permanent --add-port=81/tcp
sudo firewall-cmd --zone=public --permanent --add-port=90/tcp
sudo firewall-cmd --zone=public --permanent --add-port=110/tcp
sudo firewall-cmd --zone=public --permanent --add-port=143/tcp
sudo firewall-cmd --zone=public --permanent --add-port=442/tcp
sudo firewall-cmd --zone=public --permanent --add-port=443/tcp
sudo firewall-cmd --zone=public --permanent --add-port=444/tcp
sudo firewall-cmd --zone=public --permanent --add-port=8080/tcp
sudo firewall-cmd --zone=public --permanent --add-port=8081/tcp
sudo firewall-cmd --zone=public --permanent --add-port=5300/udp
sudo firewall-cmd --zone=public --permanent --add-port=7200/udp
sudo firewall-cmd --zone=public --permanent --add-port=7300/udp
sudo firewall-cmd --reload
sudo firewall-cmd --zone=public --list-ports &>/dev/null
msg -azu "	FIX AGREGADO"

}
cache(){
clear
msg -bar
msg -verm "	FREEING UP SYSTEM CACHÉ/RAM"
msg -bar

sysctl -w vm.drop_caches=3 &> /dev/null
#apt-get autoclean -y &>/dev/null; apt-get clean -y &>/dev/null && msg -ama " REFRESCANDO RAM,SISTEMA"| pv -qL20
#  sleep 2s

  if [[ ! -z $(crontab -l|grep -w "autolim") ]]; then
    msg -azu " Scheduled self cleaning every $(msg -verd "[ $(crontab -l|grep -w "autolim"|awk '{print $2}'|sed $'s/[^[:alnum:]\t]//g')HS ]")"
    msg -bar
    while :
    do
    echo -ne "$(msg -azu " Stop Self Cleaning [S/N]: ")" && read yesno
    tput cuu1 && tput dl1
    case $yesno in
      s|S) crontab -l > /root/cron && sed -i '/autolim/ d' /root/cron && crontab /root/cron && rm /etc/autolim
           msg -azu "Self-Clean Stopped!" && msg -bar && sleep 2
           return 1;;
      n|N)return 1;;
      *)menu3 ;;
    esac
    done
  fi 
  clear
  msg -bar
msg -ama "	  \e[1;97m\e[2;100mAUTO SYSTEM MAINTENANCE \e[0m"
msg -bar 
msg -verm2 " ➥ \e[97mPACKAGE UPDATE      "
msg -verm2 " ➥ \e[97mREFRESH RAM       "
msg -verm2 " ➥ \e[97mREFRESH SWAP       "
msg -verm2 " ➥ \e[97mCLEAN OUTDATED PACKAGES      "
msg -verm2 " ➥ \e[97mCLEAN CACHE V2RAY      "
msg -verm2 " ➥ \e[97mSSL RESET       "
msg -bar
  echo -ne "$(msg -azu "Do you want to program Self-Clean [s/n]:") "
  read c_ram
  if [[ $c_ram = @(s|S|y|Y) ]]; then
    tput cuu1 && tput dl1
    echo -ne "$(msg -azu " PUT A NUMBER, EXAMPLE [1-12 HOURS]:") "
    read ram_c
    if [[ $ram_c =~ ^[0-9]+$ ]]; then
      crontab -l > /root/cron
      wget -O /etc/autolim https://www.dropbox.com/s/rro6ghqr1dsj20l/autolim.sh &>/dev/null
		chmod 777 /etc/autolim
      echo "0 */$ram_c * * * bash /etc/autolim" >> /root/cron
      crontab /root/cron
      
      service cron restart
      rm /root/cron
      tput cuu1 && tput dl1
      msg -azu " Scheduled Self-Cleaning every: $(msg -verd "${ram_c} HORAS")" && msg -bar && sleep 2
    else
      tput cuu1 && tput dl1
      msg -verm2 " enter only numbers between 1 and 12"
      sleep 2
      msg -bar
    fi
  fi
  return 1
}

pidr_inst(){
  proto="dropbear python stunnel4 stunnel5 v2ray node badvpn squid openvpn dns-serve ssserver ss-server"
  portas=$(lsof -V -i -P -n | grep -v "ESTABLISHED" |grep -v "COMMAND")
  for list in $proto; do
    case $list in
      dropbear|python|stunnel4|stunnel5|v2ray|node|badvpn|squid|openvpn|ssserver|ss-server)
      portas2=$(echo $portas|grep -w "LISTEN"|grep -w "$list")
      [[ $(echo "${portas2}"|grep "$list") ]] && inst[$list]="\033[1;32m[ON] " || inst[$list]="\033[1;31m[OFF]";;
      dns-serve)
      portas2=$(echo $portas|grep -w "$list")
      [[ $(echo "${portas2}"|grep "$list") ]] && inst[$list]="\033[1;32m[ON] " || inst[$list]="\033[1;31m[OFF]";;
    esac
  done
  [[ $(dpkg --get-selections|grep -w 'wireguard'|head -1) ]] && {
    if [[ $(wg|grep -w 'interface') = "" ]]; then inst[wg]="\033[1;31m[OFF]"; else inst[wg]="\033[1;32m[ON] "; fi
  } || {
    inst[wg]="\033[1;31m[OFF]"
  }
}
# Menu Instalaciones

#check_IP&
# MENU FLUTUANTE
menu_func () {
local options=${#@}
local array
for((num=1; num<=$options; num++)); do
echo -ne "  $(msg -verd "\e[1;93m[\e[92m$num\e[93m]") $(msg -verm2 "➛ ") "
  array=(${!num})
  case ${array[0]} in
    "-vd")msg -verd "\033[1;33m[!]\033[1;32m $(fun_trans "${array[@]:1}")" | sed ':a;N;$!ba;s/\n/ /g';;
    "-vm")msg -verm2 "\033[1;33m[!]\033[1;31m $(fun_trans "${array[@]:1}")" | sed ':a;N;$!ba;s/\n/ /g';;
    "-fi")msg -azu "$(fun_trans "${array[@]:2}") ${array[1]}" | sed ':a;N;$!ba;s/\n/ /g';;
    *)msg -azu "$(fun_trans "${array[@]}")" | sed ':a;N;$!ba;s/\n/ /g';;
  esac
done
}

VERY3=$(ps aux|grep -v grep|grep "monitor")
monservi_fun () {
clear
clear
monssh () {
sed -i "57d" /bin/monitor.sh
sed -i '57i ssh service status' /bin/monitor.sh
}
mondropbear () {
sed -i "59d" /bin/monitor.sh
sed -i '59i Dropbear Service Status' /bin/monitor.sh
}
monssl() {
sed -i "61d" /bin/monitor.sh
sed -i '61i StatusService stunnel4' /bin/monitor.sh
}
monsquid() {
sed -i "63d" /bin/monitor.sh
sed -i '63i [[ $(EstadoServicio squid) ]] && EstadoServicio squid3' /bin/monitor.sh
}
monapache() {
sed -i "65d" /bin/monitor.sh
sed -i '65i EstadoServicio apache2' /bin/monitor.sh
}
monv2ray() {
sed -i "55d" /bin/monitor.sh
sed -i '55i StatusService v2ray' /bin/monitor.sh
}
msg -bar
msg -tit
echo -e "\033[1;32m          MAIN SERVICES MONITOR"

PIDVRF3=$(ps aux|grep -v grep |grep "monitor")

#PIDVRF5=$(ps x|grep -v grep |grep "monit") 

if [[ -z $PIDVRF3 ]]; then
#sed -i '5a\screen -dmS monitor /etc/VPS-MX/tmp/monitor' /bin/resetsshdrop
msg -bar
echo -e "\033[1;34m          ¿Monitor protocol ssh/sshd?"
msg -bar
read -p "                    [ s | n ]: " monssh  
sed -i "57d" /bin/monitor.sh
sed -i '57i #EstadoServicio ssh' /bin/monitor.sh 
[[ "$monssh" = "s" || "$monssh" = "S" ]] && monssh
msg -bar
echo -e "\033[1;34m          ¿Monitor DROPBEAR Protocol?"
msg -bar
read -p "                    [ s | n ]: " mondropbear  
sed -i "59d" /bin/monitor.sh
sed -i '59i #Dropbear Service Status' /bin/monitor.sh
[[ "$mondropbear" = "s" || "$mondropbear" = "S" ]] && mondropbear
msg -bar
echo -e "\033[1;34m            ¿Monitor SSL Protocol?"
msg -bar
read -p "                    [ s | n ]: " monssl  
sed -i "61d" /bin/monitor.sh
sed -i '61i #StatusService stunnel4' /bin/monitor.sh
[[ "$monssl" = "s" || "$monssl" = "S" ]] && monssl
msg -bar
echo -e "\033[1;34m            ¿Monitor SQUID Protocol?"
msg -bar
read -p "                    [ s | n ]: " monsquid  
sed -i "63d" /bin/monitor.sh
sed -i '63i #[[ $(EstadoServicio squid) ]] && squid3 ServiceState' /bin/monitor.sh
[[ "$monsquid" = "s" || "$monsquid" = "S" ]] && monsquid
msg -bar
echo -e "\033[1;34m            ¿Monitor APACHE Protocol?"
msg -bar
read -p "                    [ s | n ]: " monapache  
sed -i "65d" /bin/monitor.sh
sed -i '65i #Service State apache2' /bin/monitor.sh
[[ "$monapache" = "s" || "$monapache" = "S" ]] && monapache
msg -bar
echo -e "\033[1;34m            ¿Monitor V2RAY Protocol?"
msg -bar
read -p "                    [ s | n ]: " monv2ray  
sed -i "55d" /bin/monitor.sh
sed -i '55i #StatusService v2ray' /bin/monitor.sh 
[[ "$monv2ray" = "s" || "$monv2ray" = "S" ]] && monv2ray 
#screen -dmS monitor /etc/VPS-MX/tmp/monitor
#screen -dmS monit /etc/VPS-MX/tmp/monitor
echo -e "[Unit]
Description=monitor Service
After=network.target\n
[Service]
Type=simple
User=root
WorkingDirectory=/root
ExecStart=/bin/bash /etc/VPS-MX/tmp/monitor
Restart=always
RestartSec=3s\n
[Install]
WantedBy=multi-user.target" > /etc/systemd/system/monit.service

    systemctl enable monit &>/dev/null
    systemctl start monit &>/dev/null
else

	systemctl stop monit &>/dev/null
	systemctl disable monit &>/dev/null
    rm -rf /etc/systemd/system/monit .service
    sed -i "6d" /bin/resetsshdrop
fi

msg -bar
echo -e "             You can monitor from:\n       \033[1;32m http://$(meu_ip):81/monitor.html"
msg -bar
[[ -z ${VERY3} ]] && monitor="\033[1;32m ACTIVATED " || monitor="\033[1;31m DISABLED "
echo -e "            $monitor  --  CON EXITO"
msg -bar

}
droppids(){
  port_dropbear=`ps aux|grep 'dropbear'|awk NR==1|awk '{print $17;}'`

  log=/var/log/auth.log
  loginsukses='Password auth succeeded'

  pids=`ps ax|grep 'dropbear'|grep " $port_dropbear"|awk -F " " '{print $1}'`

  for pid in $pids; do
    pidlogs=`grep $pid $log |grep "$loginsukses" |awk -F" " '{print $3}'`

    i=0
    for pidend in $pidlogs; do
      let i=i+1
    done

    if [ $pidend ];then
       login=`grep $pid $log |grep "$pidend" |grep "$loginsukses"`
       PID=$pid
       user=`echo $login |awk -F" " '{print $10}' | sed -r "s/'/ /g"`
       waktu=`echo $login |awk -F" " '{print $2"-"$1,$3}'`
       while [ ${#waktu} -lt 13 ]; do
           waktu=$waktu" "
       done
       while [ ${#user} -lt 16 ]; do
           user=$user" "
       done
       while [ ${#PID} -lt 8 ]; do
           PID=$PID" "
       done
       echo "$user $PID $waktu"
    fi
done
}
openvpn_pids () {
#nome|#loguin|#rcv|#snd|#time
  byte () {
   while read B dummy; do
   [[ "$B" -lt 1024 ]] && echo "${B} bytes" && break
   KB=$(((B+512)/1024))
   [[ "$KB" -lt 1024 ]] && echo "${KB} Kb" && break
   MB=$(((KB+512)/1024))
   [[ "$MB" -lt 1024 ]] && echo "${MB} Mb" && break
   GB=$(((MB+512)/1024))
   [[ "$GB" -lt 1024 ]] && echo "${GB} Gb" && break
   echo $(((GB+512)/1024)) terabytes
   done
   }
for user in $(mostrar_usuarios); do
user="$(echo $user|sed -e 's/[^a-z0-9 -]//ig')"
[[ ! $(sed -n "/^${user},/p" /etc/openvpn/openvpn-status.log) ]] && continue
i=0
unset RECIVED; unset SEND; unset HOUR
 while read line; do
 IDLOCAL=$(echo ${line}|cut -d',' -f2)
 RECIVED+="$(echo ${line}|cut -d',' -f3)+"
 SEND+="$(echo ${line}|cut -d',' -f4)+"
 DATESEC=$(date +%s --date="$(echo ${line}|cut -d',' -f5|cut -d' ' -f1,2,3,4)")
 TIMEON="$(($(date +%s)-${DATESEC}))"
  MIN=$(($TIMEON/60)) && SEC=$(($TIMEON-$MIN*60)) && HOR=$(($MIN/60)) && MIN=$(($MIN-$HOR*60))
  HOUR+="${HOR}h:${MIN}m:${SEC}s\n"
  let i++
 done <<< "$(sed -n "/^${user},/p" /etc/openvpn/openvpn-status.log)"
RECIVED=$(echo $(echo ${RECIVED}0|bc)|byte)
SEND=$(echo $(echo ${SEND}0|bc)|byte)
HOUR=$(echo -e $HOUR|sort -n|tail -1)
echo -e "$user|$i|$RECIVED|$SEND|$HOUR" 
done
}
monitor-user(){
	users=$(cat /etc/passwd|grep 'home'|grep 'false'|grep -v 'syslog'|awk -F ':' '{print $1}')
	dpids=$(droppids)
	time=$(date +%s)
	[[ -e /etc/openvpn/openvpn-status.log ]] && ovpn_log=$(cat /etc/openvpn/openvpn-status.log)

	n='0'
	i='0'
	conect='0'
	for _user in $users; do
		[[ -z "$(ps -u $_user|grep sshd)" ]] && sqd=0 || sqd=1
		[[ -z "$(echo $ovpn_log|grep -E ,"$_user",)" ]] && ovp=0 || ovp=1
        [[ -z "$(echo $dpids|grep -w "$_user")" ]] && drop=0 || drop=1

        conex=$(($sqd + $ovp + $drop))
    #   conex="$(echo $PID|bc)"
        [[ $conex -ne 0 ]] && let conect++

		if [[ $(chage -l $_user |grep 'Account expires' |awk -F ': ' '{print $2}') != never ]]; then
			[[ $time -gt $(date '+%s' -d "$(chage -l $_user |grep "Account expires" |awk -F ': ' '{print $2}')") ]] && let n++
		fi
		[[ $(passwd --status $_user|cut -d ' ' -f2) = "L" ]] && let i++
	done

	_onlin=$(printf '%-7s' "$conect")
	_userexp=$(printf '%-7s' "$n")
	_lok=$(printf '%-7s' "$i")
	_tuser=$(echo "$users"|sed '/^$/d'|wc -l)

	echo -e " $(msg -verd "ONLINE:") $(msg -azu "$_onlin") $(msg -verm2 "EXPIRED:") $(msg -azu "$_userexp") $(msg -bra "\e[95mBLOQUEADO:") $(msg -azu "$_lok")" #$(msg -ama "TOTAL:") $(msg -azu "$_tuser")"
}
# SISTEMA DE SELECAO
selection_fun () {
local selection="null"
local range
for((i=0; i<=$1; i++)); do range[$i]="$i "; done
while [[ ! $(echo ${range[*]}|grep -w "$selection") ]]; do
echo -ne "\033[1;37m$(fun_trans " ► Select an Option"): " >&2
read selection
tput cuu1 >&2 && tput dl1 >&2
done
echo $selection
}
export -f msg
export -f selection_fun
export -f fun_trans
export -f menu_func
export -f meu_ip
export -f fun_ip
export -f lacasita
clear
sudo sync
sudo sysctl -w vm.drop_caches=3 > /dev/null 2>&1
clear
clear
#msg -lol
msg -bar3
msg -tit
#
menu_info
msg -bar
# echo -e "\033[1;31m[\033[1;32m $vesaoSCT\033[1;97m"
# msg -bar
title=`echo -e "\033[1;96m$(cat ${SCPdir}/message.txt)"`
printf "%*s\n" $(( ( $(echo -e "$title" | wc -c ) + 55 ) / 2 )) "$title"
msg -bar

SSHN="$(grep -c home /etc/passwd)"
#SSH2="$(echo ${SSHN}|bc)-2"
echo "${SSHN}"|bc > /etc/VPS-MX/controlador/SSH20.log
SSH3="$(less /etc/VPS-MX/controlador/SSH20.log)"
SSH4="$(echo $SSH3)"
user_info=$(cd /usr/local/shadowsocksr &> /dev/null  && python mujson_mgr.py -l ) 
user_total=$(echo "${user_info}"|wc -l)
[[ ! -e /etc/VPS-MX/RegV2ray ]] && touch /etc/VPS-MX/RegV2ray
vray=$(cat /etc/VPS-MX/RegV2ray | wc -l)
on="\033[1;92m[ON]" && off="\033[1;31m[OFF]"
#[[ $(ps x | grep badvpn | grep -v grep | awk '{print $1}') ]] && badvpn=$on || badvpn=$off
echo -e "\033[1;97m   SSH REG:\033[1;92m $SSH4 \033[1;97m   SS-SSRR REG:\033[1;92m $user_total \033[1;97m   V2RAY REG:\e[32m $vray"
limseg="$(less /etc/VPS-MX/controlador/tiemlim.log)" 
veri=$(ps x|grep -v grep |grep "verif")
[[ ! $veri ]] && verificar="\033[1;31m[OFF]" || verificar="\033[1;32m[ON] "
des=$(ps x|grep -v grep |grep "autode")
[[ ! $des ]] && desbloqueo="\033[1;31m[OFF]" || desbloqueo="\033[1;32m[ON] "
mon=$(ps x|grep -v grep |grep "monitor")
[[ ! $mon ]] && monitorserv="\033[1;31m[OFF]" || monitorserv="\033[1;32m[ON] "

if [[ ! -e ${SCPdir}/USRonlines ]]; then
if [[ $(cat ${SCPdir}/tmp/style|grep -w "monitor-user"|awk '{print $2}') = "1" ]] ; then
  monitor-user
#  msg -bar
fi

else
[[ -e ${SCPdir}/USRonlines ]] && msg -bar && msg -ne "\033[1;97m LIMITER:\033[1;92m$verificar \033[1;97m SELF-UNLOCK:\033[1;92m$desbloqueo \e[1;97mMONITOR:\e[34m${limseg}s\n \033[1;32mCONNECTED: " && echo -ne "\033[1;97m$(cat ${SCPdir}/USRonlines) "
[[ -e ${SCPdir}/USRexpired ]] && msg -ne "   EXPIRED: " && echo -ne "\033[1;97m$(cat ${SCPdir}/USRexpired) "  && msg -ne " \033[1;95m BLOCKED: " && echo -e "\033[1;97m$(cat ${SCPdir}/USRbloqueados)" #\n\033[1;97m        ACTULIZACION DE MONITOR CADA: \033[1;34m $limseg s" 
fi
monhtop () {
clear 

#msg -bar
msg -tit
echo -ne " \033[1;93m             HTOP PROCESSES MONITOR\n"
msg -bar
msg -bra "    REMEMBER TO GO OUT WITH : \033[1;96m CTRL + C o FIN + F10 "
[[ $(dpkg --get-selections|grep -w "htop"|head -1) ]] || apt-get install htop -y &>/dev/null
msg -bar
read -t 10 -n 1 -rsp $'\033[1;39m Press enter to continue\n'
clear
sudo htop
msg -bar
echo -e "\e[97m \033[1;41m| #-#-►  SCRIPT VPS•MX ◄-#-# | \033[1;49m\033[1;49m \033[1;31m[ \033[1;32m $vesaoSCT      "
echo -ne " \033[1;93m             HTOP PROCESSES MONITOR\n"
msg -bar
echo -e "\e[97m                  END OF MONITOR"
msg -bar
}

[[ $(ps x | grep v2ray | grep -v grep | awk '{print $1}') ]] && vra=$on || vra=$off
msg -bar
msg -bar3
on="\e[1;32m[ON]" && off="\e[1;31m[OFF]"
echo -e " \e[1;93m[\e[92m1\e[93m] $(msg -verm2 "➛ ") $(msg -azu "ADMINISTRAR CUENTAS | SSH/SSL/DROPBEAR")" 
echo -e " \e[1;93m[\e[92m2\e[93m] $(msg -verm2 "➛ ") $(msg -azu "ADMINISTRAR CUENTAS | SS/SSRR")" 
echo -e " \e[1;93m[\e[92m3\e[93m] $(msg -verm2 "➛ ") $(msg -azu "ADMINISTRAR CUENTAS | V2RAY --> $vra")"
echo -e " \e[1;93m[\e[92m4\e[93m] $(msg -verm2 "➛ ") \e[1;31m\033[47mPROTOCOLOS\e[0m  \e[93m||  \e[1;37m\e[41mHERRAMIENTAS\e[0m"
echo -e " \e[1;93m[\e[92m5\e[93m] $(msg -verm2 "➛ ") $(msg -azu "MONITOR DE PROTOCOLOS --------> ${monitorserv}")"
echo -e " \e[1;93m[\e[92m6\e[93m] $(msg -verm2 "➛ ") $(msg -azu "AUTO INICIAR SCRIPT ----------> $AutoRun ")"
msg -bar
echo -e " \e[1;93m[\e[92m7\e[93m] \e[97m$(msg -verm2 "➛ ") $(msg -verd "UPDATE") \e[1;93m [\e[92m8\e[93m]\e[97m$(msg -verm2 "➛ ")\033[1;31mUNINSTALL  \e[1;93m[\e[92m0\e[93m]$(msg -verm2 "➛ ") $(msg -bra "\e[97m\033[1;41mGO OUT")"
msg -bar

selection=$(selection_fun 13)
case ${selection} in
1)${SCPusr}/usercodes ;;
2)${SCPinst}/C-SSR.sh ;;
3)${SCPinst}/v2ray.sh ;;
4)menu3;;
5) monservi_fun ;; #/etc/VPS-MX/tmp/monitor;;
6)fun_autorun;;
7)atualiza_fun;;
8)remove_script;;
0)cd $HOME && exit 0;;
esac
msg -ne "Enter to continue" && read enter
${SCPdir}/menu
