#!/bin/bash

donar () {
			 bot_retorno="$LINE\n"
			 bot_retorno+="        ⚠️ TENDRAS ACCESO ILIMITADO ⚠️ \n          🚫 INCLUIDO TU RESELLER EN LA KEY 🚫"
			 bot_retorno+=" 𝙴𝚜𝚝𝚎 𝙿𝚛𝚘𝚢𝚎𝚌𝚝𝚘, 𝚗𝚎𝚌𝚎𝚜𝚒𝚝𝚊 𝚊𝚢𝚞𝚍𝚊 𝚙𝚊𝚛𝚊 𝙴𝚟𝚘𝚕𝚞𝚌𝚒𝚘𝚗𝚊𝚛\n"
			 bot_retorno+="          𝙎𝙞 𝙙𝙚𝙨𝙚𝙖𝙨 𝙍𝙚𝙖𝙡𝙞𝙯𝙖𝙧 𝙪𝙣𝙖 𝘿𝙤𝙣𝙖𝙘𝙞𝙤𝙣\n"
			 bot_retorno+="                     𝙋𝙖𝙮𝙥𝙖𝙡\n"
			 bot_retorno+="            PAGO BTC - CRIPTOMONEDA\n"
			 bot_retorno+="$LINE\n"
			 bot_retorno+=" Desde ya muchas gracias\n"
			 bot_retorno+="$LINE\n"
			 msj_fun 
			 #msj_donar
}

donar_OnOff () {
if [[ ! -e "/etc/donar_active.txt" ]]; then
	echo "on" > /etc/donar_active.txt
	local bot_retorno="$LINE\n"
          bot_retorno+="MENSAJE DONATIVO : <u>ENCENDIDO</u> ✅\n"
	  bot_retorno+="$LINE\n"
	msj_fun
else
	rm -rf /etc/donar_active.txt
	local bot_retorno="$LINE\n"
          bot_retorno+="MENSAJE DONATIVO: <u>APAGADO</u> ❌\n"
	  bot_retorno+="$LINE\n"
	msj_fun
fi
}
